### ISSUE TITLE
Bestellung genehmigen

### ISSUE THREAD

**Issue by akramer-dozent** [akramer-dozent/beispielprojekt-erp#2]
Eine Liste in der die Bestellungen aufgelistet werden und in der man die Bestellung genehmigen kann.

**Comment by kramer-fuer-dhbw** [comment]
Benötigt das Feature, dass neue Bestellungen persistiert und jederzeit abgerufen werden können

**Comment by akramer-dozent** [comment]
Pull Request https://github.com/akramer-dozent/beispielprojekt-erp/pull/8

**Comment by akramer-dozent** [comment]
umgesetzt
